- name: get package
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common

- name: add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present

- name: install docker-ce
  apt:
    name:
      - docker-ce
    update_cache: yes

- name: enable docker
  systemd:
    name: docker
    state: started
    enabled: true
